/* SPDX-License-Identifier: GPL-2.0 */
/* Microchip LAN937X switch register definitions
 * Copyright (C) 2019-2020 Microchip Technology Inc.
 */
#ifndef __LAN937X_REG_H
#define __LAN937X_REG_H

/* 0 - Operation */
#define REG_CHIP_ID0__1			0x0000
#define REG_CHIP_ID1__1			0x0001
#define REG_CHIP_ID2__1			0x0002

#define CHIP_ID_74			0x74
#define CHIP_ID_73			0x73
#define CHIP_ID_72			0x72
#define CHIP_ID_71			0x71
#define CHIP_ID_70			0x70

#define REG_CHIP_ID3__1			0x0003

#define REG_GLOBAL_CTRL_0		0x0007

#define SW_PHY_REG_BLOCK		BIT(7)
#define SW_FAST_MODE			BIT(3)
#define SW_FAST_MODE_OVERRIDE		BIT(2)

#define REG_GLOBAL_OPTIONS		0x000F

#define REG_SW_INT_STATUS__4		0x0010
#define REG_SW_INT_MASK__4		0x0014

#define LUE_INT				BIT(31)
#define TRIG_TS_INT			BIT(30)
#define APB_TIMEOUT_INT			BIT(29)
#define OVER_TEMP_INT			BIT(28)
#define HSR_INT				BIT(27)
#define PIO_INT				BIT(26)
#define POR_READY_INT			BIT(25)

#define SWITCH_INT_MASK			\
	(LUE_INT | TRIG_TS_INT | APB_TIMEOUT_INT | OVER_TEMP_INT | HSR_INT | \
	 PIO_INT | POR_READY_INT)

#define REG_SW_PORT_INT_STATUS__4	0x0018
#define REG_SW_PORT_INT_MASK__4		0x001C

/* 1 - Global */
#define REG_SW_GLOBAL_SERIAL_CTRL_0	0x0100

#define SW_LITTLE_ENDIAN		BIT(4)
#define SPI_AUTO_EDGE_DETECTION		BIT(1)
#define SPI_CLOCK_OUT_RISING_EDGE	BIT(0)

#define REG_SW_GLOBAL_OUTPUT_CTRL__1	0x0103
#define SW_ENABLE_REFCLKO		BIT(1)
#define SW_REFCLKO_IS_125MHZ		BIT(0)

/* 2 - PHY */
#define REG_SW_POWER_MANAGEMENT_CTRL	0x0201

/* 3 - Operation Control */
#define REG_SW_OPERATION		0x0300

#define SW_DOUBLE_TAG			BIT(7)
#define SW_OVER_TEMP_ENABLE		BIT(2)
#define SW_RESET			BIT(1)
#define SW_START			BIT(0)

#define REG_SW_LUE_CTRL_0		0x0310
#define SW_VLAN_ENABLE			BIT(7)
#define SW_DROP_INVALID_VID		BIT(6)
#define SW_AGE_CNT_M			0x7
#define SW_AGE_CNT_S			3
#define SW_RESV_MCAST_ENABLE		BIT(2)

#define REG_SW_LUE_CTRL_1		0x0311

#define UNICAST_LEARN_DISABLE		BIT(7)
#define SW_SRC_ADDR_FILTER		BIT(6)
#define SW_FLUSH_STP_TABLE		BIT(5)
#define SW_FLUSH_MSTP_TABLE		BIT(4)
#define SW_FWD_MCAST_SRC_ADDR		BIT(3)
#define SW_AGING_ENABLE			BIT(2)
#define SW_FAST_AGING			BIT(1)
#define SW_LINK_AUTO_AGING		BIT(0)

#define REG_SW_LUE_CTRL_2		0x0312

#define SW_MID_RANGE_AGE		BIT(7)
#define SW_LINK_DOWN_FLUSH		BIT(6)
#define SW_EGRESS_VLAN_FILTER_DYN	BIT(5)
#define SW_EGRESS_VLAN_FILTER_STA	BIT(4)
#define SW_FLUSH_OPTION_M		0x3
#define SW_FLUSH_OPTION_S		2
#define SW_FLUSH_OPTION_DYN_MAC		1
#define SW_FLUSH_OPTION_STA_MAC		2
#define SW_FLUSH_OPTION_BOTH		3

#define REG_SW_LUE_CTRL_3		0x0313
#define REG_SW_AGE_PERIOD__1		0x0313

#define REG_SW_LUE_INT_STATUS__1	0x0314
#define REG_SW_LUE_INT_MASK__1		0x0315

#define LEARN_FAIL_INT			BIT(2)
#define WRITE_FAIL_INT			BIT(0)

#define LUE_INT_MASK			(LEARN_FAIL_INT | WRITE_FAIL_INT)

#define REG_SW_LUE_INDEX_0__2		0x0316

#define ENTRY_INDEX_M			0x0FFF

#define REG_SW_LUE_INDEX_1__2		0x0318

#define FAIL_INDEX_M			0x03FF

#define REG_SW_LUE_INDEX_2__2		0x031A

#define REG_SW_STATIC_AVAIL_ENTRY__4	0x031C

#define SW_INGRESS_FILTERING_NO_LEARN	BIT(15)
#define SW_STATIC_AVAIL_CNT		0x1FF

#define REG_SW_AGE_PERIOD__2		0x0320
#define SW_AGE_PERIOD_M			0xFFF

#define REG_SW_LUE_UNK_UCAST_CTRL__2	0x0322
#define REG_SW_LUE_UNK_CTRL_0__4	0x0322

#define SW_UNK_UCAST_ENABLE		BIT(15)
#define SW_UNK_PORTS_M			0xFF

#define REG_SW_LUE_UNK_MCAST_CTRL__2	0x0324
#define SW_UNK_MCAST_ENABLE		BIT(15)

#define REG_SW_LUE_UNK_VID_CTRL__2	0x0326
#define SW_UNK_VID_ENABLE		BIT(15)

#define SW_VLAN_FLUSH_PORTS_M		0xFF

#define REG_SW_STATIC_ENTRY_LIMIT__4	0x032C

#define REG_SW_MAC_CTRL_0			0x0330
#define SW_NEW_BACKOFF			BIT(7)
#define SW_PAUSE_UNH_MODE		BIT(1)
#define SW_AGGR_BACKOFF			BIT(0)

#define REG_SW_MAC_CTRL_1		0x0331
#define SW_SHORT_IFG			BIT(7)
#define MULTICAST_STORM_DISABLE		BIT(6)
#define SW_BACK_PRESSURE		BIT(5)
#define FAIR_FLOW_CTRL			BIT(4)
#define NO_EXC_COLLISION_DROP		BIT(3)
#define SW_LEGAL_PACKET_DISABLE		BIT(1)
#define SW_PASS_SHORT_FRAME		BIT(0)

#define REG_SW_MAC_CTRL_2		0x0332
#define SW_REPLACE_VID			BIT(3)
#define BROADCAST_STORM_RATE_HI		0x07

#define REG_SW_MAC_CTRL_3		0x0333
#define BROADCAST_STORM_RATE_LO		0xFF
#define BROADCAST_STORM_RATE		0x07FF

#define REG_SW_MAC_CTRL_4		0x0334
#define SW_PASS_PAUSE			BIT(3)

#define REG_SW_MAC_CTRL_5		0x0335
#define SW_OUT_RATE_LIMIT_QUEUE_BASED	BIT(3)

#define REG_SW_MAC_CTRL_6		0x0336
#define SW_MIB_COUNTER_FLUSH		BIT(7)
#define SW_MIB_COUNTER_FREEZE		BIT(6)

#define REG_SW_MRI_CTRL_0		0x0370
#define SW_IGMP_SNOOP			BIT(6)
#define SW_IPV6_MLD_OPTION		BIT(3)
#define SW_IPV6_MLD_SNOOP		BIT(2)
#define SW_MIRROR_RX_TX			BIT(0)

#define REG_SW_MRI_CTRL_1__4		0x0374
#define REG_SW_MRI_CTRL_2__4		0x0378
#define REG_SW_CLASS_D_IP_CTRL__4	0x0374

#define SW_CLASS_D_IP_ENABLE		BIT(31)

#define REG_SW_MRI_CTRL_8		0x0378
#define SW_RED_COLOR_S			4
#define SW_YELLOW_COLOR_S		2
#define SW_GREEN_COLOR_S		0
#define SW_COLOR_M			0x3

#define REG_PTP_EVENT_PRIO_CTRL		0x037C
#define REG_PTP_GENERAL_PRIO_CTRL	0x037D
#define PTP_PRIO_ENABLE			BIT(7)

#define REG_SW_QM_CTRL__4		0x0390
#define PRIO_SCHEME_SELECT_M		KS_PRIO_M
#define PRIO_SCHEME_SELECT_S		6
#define PRIO_MAP_3_HI			0
#define PRIO_MAP_2_HI			2
#define PRIO_MAP_0_LO			3
#define UNICAST_VLAN_BOUNDARY		BIT(1)

#define REG_SW_EEE_QM_CTRL__2		0x03C0
#define REG_SW_EEE_TXQ_WAIT_TIME__2	0x03C2

/* 4 - */
#define REG_SW_VLAN_ENTRY__4		0x0400
#define VLAN_VALID			BIT(31)
#define VLAN_FORWARD_OPTION		BIT(27)
#define VLAN_PRIO_M			KS_PRIO_M
#define VLAN_PRIO_S			24
#define VLAN_MSTP_M			0x7
#define VLAN_MSTP_S			12
#define VLAN_FID_M			0x7F

#define REG_SW_VLAN_ENTRY_UNTAG__4	0x0404
#define REG_SW_VLAN_ENTRY_PORTS__4	0x0408
#define REG_SW_VLAN_ENTRY_INDEX__2	0x040C

#define VLAN_INDEX_M			0x0FFF

#define REG_SW_VLAN_CTRL		0x040E
#define VLAN_START			BIT(7)
#define VLAN_ACTION			0x3
#define VLAN_WRITE			1
#define VLAN_READ			2
#define VLAN_CLEAR			3

#define REG_SW_ALU_INDEX_0		0x0410
#define ALU_FID_INDEX_S			16
#define ALU_FID_SIZE			127
#define ALU_MAC_ADDR_HI			0xFFFF

#define REG_SW_ALU_INDEX_1		0x0414
#define ALU_DIRECT_INDEX_M		(BIT(12) - 1)

#define REG_SW_ALU_CTRL__4		0x0418
#define REG_SW_ALU_CTRL(num)	(REG_SW_ALU_CTRL__4 + ((num) * 4))

#define ALU_STA_DYN_CNT			2
#define ALU_VALID_CNT_M			(BIT(14) - 1)
#define ALU_VALID_CNT_S			16
#define ALU_START			BIT(7)
#define ALU_VALID			BIT(6)
#define ALU_VALID_OR_STOP		BIT(5)
#define ALU_DIRECT			BIT(2)
#define ALU_ACTION			0x3
#define ALU_WRITE			1
#define ALU_READ			2
#define ALU_SEARCH			3

#define REG_SW_ALU_STAT_CTRL__4		0x041C
#define ALU_STAT_VALID_CNT_M		(BIT(9) - 1)
#define ALU_STAT_VALID_CNT_S		20
#define ALU_STAT_INDEX_M		(BIT(8) - 1)
#define ALU_STAT_INDEX_S		8
#define ALU_RESV_MCAST_INDEX_M		(BIT(6) - 1)
#define ALU_STAT_START			BIT(7)
#define ALU_STAT_VALID			BIT(6)
#define ALU_STAT_VALID_OR_STOP		BIT(5)
#define ALU_STAT_USE_FID		BIT(4)
#define ALU_STAT_DIRECT			BIT(3)
#define ALU_RESV_MCAST_ADDR		BIT(2)
#define ALU_STAT_ACTION			0x3
#define ALU_STAT_WRITE			1
#define ALU_STAT_READ			2
#define ALU_STAT_SEARCH			3

#define REG_SW_ALU_VAL_A		0x0420
#define ALU_V_STATIC_VALID		BIT(31)
#define ALU_V_SRC_FILTER		BIT(30)
#define ALU_V_DST_FILTER		BIT(29)
#define ALU_V_PRIO_AGE_CNT_M		(BIT(3) - 1)
#define ALU_V_PRIO_AGE_CNT_S		26
#define ALU_V_MSTP_M			0x7

#define REG_SW_ALU_VAL_B		0x0424
#define ALU_V_OVERRIDE			BIT(31)
#define ALU_V_USE_FID			BIT(30)
#define ALU_V_PORT_MAP			0xFF

#define REG_SW_ALU_VAL_C		0x0428
#define ALU_V_FID_M			(BIT(16) - 1)
#define ALU_V_FID_S			16
#define ALU_V_MAC_ADDR_HI		0xFFFF

#define REG_SW_ALU_VAL_D		0x042C

#define PORT_CTRL_ADDR(port, addr)	((addr) | (((port) + 1)  << 12))

#define REG_GLOBAL_RR_INDEX__1		0x0600

/* VPHY */
#define REG_VPHY_CTRL__2		0x0700
#define REG_VPHY_STAT__2		0x0704
#define REG_VPHY_ID_HI__2		0x0708
#define REG_VPHY_ID_LO__2		0x070C
#define REG_VPHY_AUTO_NEG__2		0x0710
#define REG_VPHY_REMOTE_CAP__2		0x0714

#define REG_VPHY_EXPANSION__2		0x0718

#define REG_VPHY_M_CTRL__2		0x0724
#define REG_VPHY_M_STAT__2		0x0728

#define REG_VPHY_EXT_STAT__2		0x073C
#define VPHY_EXT_1000_X_FULL		BIT(15)
#define VPHY_EXT_1000_X_HALF		BIT(14)
#define VPHY_EXT_1000_T_FULL		BIT(13)
#define VPHY_EXT_1000_T_HALF		BIT(12)

#define REG_VPHY_DEVAD_0__2		0x0740
#define REG_VPHY_DEVAD_1__2		0x0744
#define REG_VPHY_DEVAD_2__2		0x0748
#define REG_VPHY_DEVAD_3__2		0x074C

#define VPHY_DEVAD_UPDATE		BIT(7)
#define VPHY_DEVAD_M			0x1F
#define VPHY_DEVAD_S			8

#define REG_VPHY_SMI_ADDR__2		0x0750
#define REG_VPHY_SMI_DATA_LO__2		0x0754
#define REG_VPHY_SMI_DATA_HI__2		0x0758

#define REG_VPHY_IND_ADDR__2		0x075C
#define REG_VPHY_IND_DATA__2		0x0760
#define REG_VPHY_IND_CTRL__2		0x0768

#define VPHY_IND_WRITE			BIT(1)
#define VPHY_IND_BUSY			BIT(0)

#define REG_VPHY_SPECIAL_CTRL__2	0x077C
#define VPHY_SMI_INDIRECT_ENABLE	BIT(15)
#define VPHY_SW_LOOPBACK		BIT(14)
#define VPHY_MDIO_INTERNAL_ENABLE	BIT(13)
#define VPHY_SPI_INDIRECT_ENABLE	BIT(12)
#define VPHY_PORT_MODE_M		0x3
#define VPHY_PORT_MODE_S		8
#define VPHY_MODE_RGMII			0
#define VPHY_MODE_MII_PHY		1
#define VPHY_MODE_SGMII			2
#define VPHY_MODE_RMII_PHY		3
#define VPHY_SW_COLLISION_TEST		BIT(7)
#define VPHY_SPEED_DUPLEX_STAT_M	0x7
#define VPHY_SPEED_DUPLEX_STAT_S	2
#define VPHY_SPEED_1000			BIT(4)
#define VPHY_SPEED_100			BIT(3)
#define VPHY_FULL_DUPLEX		BIT(2)

/* 0 - Operation */
#define REG_PORT_DEFAULT_VID		0x0000

#define REG_PORT_CUSTOM_VID		0x0002
#define REG_PORT_PME_STATUS		0x0013

#define REG_PORT_PME_CTRL		0x0017
#define PME_WOL_MAGICPKT		BIT(2)
#define PME_WOL_LINKUP			BIT(1)
#define PME_WOL_ENERGY			BIT(0)

#define REG_PORT_INT_STATUS		0x001B
#define REG_PORT_INT_MASK		0x001F

#define PORT_TAS_INT			BIT(5)
#define PORT_SGMII_INT			BIT(3)
#define PORT_PTP_INT			BIT(2)
#define PORT_PHY_INT			BIT(1)
#define PORT_ACL_INT			BIT(0)

#define PORT_INT_MASK			\
	(				\
	PORT_TAS_INT |			\
	PORT_SGMII_INT | PORT_PTP_INT | PORT_PHY_INT | PORT_ACL_INT)

#define REG_PORT_CTRL_0			0x0020

#define PORT_MAC_LOOPBACK		BIT(7)
#define PORT_MAC_REMOTE_LOOPBACK	BIT(6)
#define PORT_K2L_INSERT_ENABLE		BIT(5)
#define PORT_K2L_DEBUG_ENABLE		BIT(4)
#define PORT_TAIL_TAG_ENABLE		BIT(2)
#define PORT_QUEUE_SPLIT_ENABLE		0x3

#define REG_PORT_CTRL_1			0x0021
#define PORT_SRP_ENABLE			0x3

#define REG_PORT_STATUS_0		0x0030
#define PORT_INTF_SPEED_M		0x3
#define PORT_INTF_SPEED_S		3
#define PORT_INTF_FULL_DUPLEX		BIT(2)
#define PORT_TX_FLOW_CTRL		BIT(1)
#define PORT_RX_FLOW_CTRL		BIT(0)

#define REG_PORT_STATUS_1		0x0034

/* 1 - PHY */
#define REG_VPHY_SMI_ADDR		0x14
#define REG_VPHY_SMI_DATA_LO		0x15
#define REG_VPHY_SMI_DATA_HI		0x16

#define REG_VPHY_SPECIAL_CTRL_STAT	0x1F

#define REG_PORT_T1_PHY_BASIC_CTRL	0x00

#define PORT_T1_PHY_RESET		BIT(15)
#define PORT_T1_PHY_LOOPBACK		BIT(14)
#define PORT_T1_SPEED_100MBIT		BIT(13)
#define PORT_T1_POWER_DOWN		BIT(11)
#define PORT_T1_ISOLATE			BIT(10)
#define PORT_T1_FULL_DUPLEX		BIT(8)

#define REG_PORT_T1_PHY_BASIC_STATUS	0x01

#define PORT_T1_MII_SUPPRESS_CAPABLE	BIT(6)
#define PORT_T1_LINK_STATUS		BIT(2)
#define PORT_T1_EXTENDED_CAPABILITY	BIT(0)

#define REG_PORT_T1_PHY_ID_HI		0x02
#define REG_PORT_T1_PHY_ID_LO		0x03

#define LAN937X_T1_ID_HI		0x0007
#define LAN937X_T1_ID_LO		0xC150

#define REG_PORT_T1_PHY_M_CTRL	0x09

#define PORT_T1_MANUAL_CFG		BIT(12)
#define PORT_T1_M_CFG		BIT(11)

#define REG_PORT_T1_PHY_M_STATUS	0x0A

#define PORT_T1_LOCAL_M		BIT(14)
#define PORT_T1_LOCAL_RX_OK		BIT(13)
#define PORT_T1_REMOTE_RX_OK		BIT(12)
#define PORT_T1_IDLE_ERR_CNT_M		0xFF

#define REG_PORT_T1_MDIO_CTRL_1		0x0F

#define T1_MDIO_WAKE_OUT_PIN_REQ	BIT(0)

#define REG_PORT_T1_MDIO_CTRL_2		0x10

#define T1_MDIO_MDPREBP			BIT(15)
#define T1_MDIO_PHYADBP			BIT(14)
#define T1_MDIO_WAKE_REQ		BIT(13)
#define T1_MDIO_SLEEP_REQ		BIT(12)
#define TI_MDIO_CTRL_CLOCK_SKEW		0x0C00
#define T1_MDIO_TX_TERNARY_SYM			0x0300
#define T1_MDIO_PCS_SC_RESET			BIT(7)
#define T1_MDIO_ENERGY_DETECT_M	BIT(6)
#define T1_MDIO_IGNORE_IDLE			BIT(5)
#define T1_MDIO_TIME_OUT_CNT			0x001E
#define T1_MDIO_TIME_OUT_ENABLE		BIT(0)

#define REG_PORT_T1_MODE_STAT			0x11
#define T1_PORT_DSCR_LOCK_STATUS_MSK	BIT(3)
#define T1_PORT_LINK_UP_MSK				BIT(0)

#define REG_PORT_T1_LOOPBACK_CTRL	0x12

#define REG_PORT_T1_RESET_CTRL		0x13

#define T1_PHYADDR_S			11

#define REG_PORT_T1_EXT_REG_CTRL	0x14

#define T1_PCS_STS_CNT_RESET		BIT(15)
#define T1_IND_DATA_READ		BIT(12)
#define T1_IND_DATA_WRITE		BIT(11)
#define T1_REG_BANK_SEL_M		0x7
#define T1_REG_BANK_SEL_S		8
#define T1_REG_BANK_SEL_INST		5
#define T1_REG_BANK_SEL_DSP		4
#define T1_REG_BANK_SEL_AFE		3
#define T1_REG_BANK_SEL_PCS		2
#define T1_REG_BANK_SEL_MISC		1
#define T1_REG_ADDR_M			0xFF

#define REG_PORT_T1_EXT_REG_RD_DATA	0x15
#define REG_PORT_T1_EXT_REG_WR_DATA	0x16

#define REG_PORT_T1_PCS_CTRL		0x17

#define REG_PORT_T1_PHY_INT_STATUS	0x18
#define REG_PORT_T1_PHY_INT_ENABLE	0x19

#define T1_PHY_CTRL_MAXWAIT_TIMER_INT	BIT(8)
#define T1_ZERO_TIMER_INT		BIT(7)
#define T1_ENERGY_OFF_INT		BIT(6)
#define T1_IDLE_ERR_THRESH_DET_INT	BIT(4)
#define T1_LINK_UP_INT			BIT(2)
#define T1_LINK_DOWN_INT		BIT(1)
#define T1_ENERGY_ON_INT		BIT(0)

#define REG_PORT_T1_POWER_DOWN_CTRL	0x1A

#define T1_BIST_LINK_UP			BIT(15)
#define T1_EMERGENCY_STOP		BIT(14)
#define T1_PTP_ENABLE			BIT(13)
#define T1_PCS_LINK_CTRL_ENABLE		BIT(12)
#define T1_DSP_START_EQUALIZER		BIT(11)
#define T1_START_ZQ_CAL			BIT(10)
#define T1_FORCE_TX_ENABLE		BIT(9)
#define T1_HW_INIT_SEQ_ENABLE		BIT(8)
#define T1_WAKE_ENABLE			BIT(7)
#define T1_LINK_UP_REQ			BIT(6)
#define T1_AUTO_CLR_EPDWRDOWN		BIT(5)
#define T1_ENERGY_DETECT_POWER_DOWN	BIT(4)
#define T1_FORCE_ENERGY_DETECT		BIT(3)
#define T1_AUTO_SLEEP_WAKEUP		BIT(2)
#define T1_ENERGY_DETECT_HW_ENABLE	BIT(1)
#define T1_ENERGY_DETECT_ENABLE		BIT(0)

#define REG_PORT_T1_BIST_CTRL		0x1B
#define REG_PORT_T1_BIST_STAT		0x1C
#define REG_PORT_T1_BIST_ERR_CNT_STS	0x1D
#define REG_PORT_T1_PCS_RX_ERR_CNT_STS	0x1E
#define REG_PORT_T1_TS_CTRL_STAT	0x1F

#define REG_PORT_T1_PCS_DESCRM_CTRL_0	0x00

#define T1_PCS_SEND_IDLE_LOC_RCV_STS	BIT(15)
#define T1_PCS_DESCR_RELOCK_ON_IDLE	BIT(14)
#define T1_PCS_DESCR_RELOCK_ON_RCV	BIT(13)
#define T1_PCS_DESCR_RELOCK_ON_EQ	BIT(12)
#define T1_PCS_DESCR_LOCK_SYM_CNT	0x0FC0
#define T1_PCS_DESCR_LOCK_CHK_WIN	0x003F

#define REG_PORT_T1_PCS_DESCRM_CTRL_1	0x01

#define T1_PCS_DESCR_PIPE_DELAY		0x0700
#define T1_PCS_FEED_DESCR_LFSR_WIN	0x003F

#define REG_PORT_T1_PCS_EQ_TIMER_CTRL	0x02

#define REG_PORT_T1_PCS_RX_ERR_CNT	0x0E

#define REG_PORT_T1_PCS_ED_STABILITY	0x26

#define REG_PORT_TX_PHY_CTRL		0x00
#define REG_PORT_TX_PHY_STATUS		0x01
#define REG_PORT_TX_PHY_ID_HI		0x02
#define REG_PORT_TX_PHY_ID_LO		0x03
#define REG_PORT_TX_PHY_AUTO_NEG	0x04
#define REG_PORT_TX_PHY_REMOTE_CAP	0x05

#define REG_PORT_TX_6			0x06
#define REG_PORT_TX_7			0x07
#define REG_PORT_TX_10			0x10
#define REG_PORT_TX_11			0x11

#define REG_PORT_TX_SPECIAL_MODES	0x12

#define TX_SPECIAL_CFG_M		0x7
#define TX_SPECIAL_CFG_S		5
#define TX_PHYADDR_M			0x1F

#define REG_PORT_TX_13			0x13

#define REG_PORT_TX_IND_CTRL		0x14

#define TX_IND_DATA_READ		BIT(15)
#define TX_IND_DATA_WRITE		BIT(14)
#define TX_REG_BANK_SEL_M		0x7
#define TX_REG_BANK_SEL_S		11
#define TX_REG_BANK_SEL_VMDAC		7
#define TX_REG_BANK_SEL_BIST		3
#define TX_REG_BANK_SEL_WOL		1
#define TX_REG_BANK_SEL_DSP		0
#define TX_TEST_MODE			BIT(10)
#define TX_READ_ADDR_M			0x1F
#define TX_READ_ADDR_S			5
#define TX_WRITE_ADDR_M			0x1F

#define REG_PORT_TX_READ_DATA_LO	0x15
#define REG_PORT_TX_READ_DATA_HI	0x16
#define REG_PORT_TX_WRITE_DATA		0x17

#define REG_PORT_TX_PHY_INT_STATUS	0x1D
#define REG_PORT_TX_PHY_INT_ENABLE	0x1E

#define TX_ENERGY_ON_INT		BIT(7)
#define TX_AUTO_NEG_COMPLETE_INT	BIT(6)
#define TX_LINK_DOWN_INT		BIT(4)
#define TX_AUTO_NEG_ACK_INT		BIT(3)
#define TX_AUTO_NEG_PAGE_RCV_INT	BIT(1)

#define REG_PORT_TX_1F			0x1F

#define TX_DSP_DCBLW			0x00

#define TX_DSP_DCBLW_VAL		0x9aa2

#define TX_DSP_A5_CONFIG		0x16

#define TX_A5_TXCLKPHSEL_M		0x7
#define TX_A5_TXCLKPHSEL_S		12
#define TX_A5_TXCLK_0_NS		0
#define TX_A5_TXCLK_1_NS		1
#define TX_A5_TXCLK_2_NS		2
#define TX_A5_TXCLK_3_NS		3
#define TX_A5_TXCLK_4_NS		4
#define TX_A5_TXCLK_5_NS		5
#define TX_A5_TXCLK_6_NS		6
#define TX_A5_TXCLK_7_NS		7

#define TX_DSP_A10_CONFIG		0x1C

#define TX_DSP_A10_CONFIG_VAL		0x9000

#define TX_DSP_A11_CONFIG		0x1D

#define TX_DSP_A11_CONFIG_VAL		0x7600

#define TX_BIST_FR_PLL_DIV0		0x1C
#define TX_BIST_FR_PLL_DIV1		0x1D

#define TX_FR_PLL_DIV0			0x0
#define TX_FR_PLL_DIV1			0x1280

#define TX_VMDAC_ZQ_CAL_CTRL		0x00

#define TX_START_ZQ_CAL			BIT(0)
#define TX_BYPASS_ZQ_CAL		BIT(1)

#define TX_VMDAC_ZQ_CAL_STAT		0x01

#define TX_VMDAC_CTRL0			0x02
#define TX_VDVREF_EN			BIT(0)
#define TX_VDVEXT_EN			BIT(1)
#define TX_A_ZEN			BIT(11)
#define TX_A_RXZEN			BIT(12)
#define TX_VD_INTIR_EN			BIT(15)

#define TX_VMDAC_CTRL0_VAL		0x9783
#define TX_VMDAC_CTRL1			0x03

#define TX_10BT_VD_EN			BIT(0)
#define TX_B_ZEN			BIT(11)
#define TX_B_RXZEN			BIT(12)
#define TX_VD_PD			BIT(15)

#define TX_VMDAC_CTRL1_VAL		0x7784
#define TX_VMDAC_MISC_PCS_CTRL0		0x05

#define TX_MISC_PCS_CTRL0_13		BIT(13)
#define TX_VMDAC_MISC_PCS_CTRL1		0x06

#define REG_PORT_T1_PHY_CTRL_BASE	0x0100
#define REG_PORT_TX_PHY_CTRL_BASE	0x0280
#define REG_TX_PHY_CTRL_BASE		0x0980

#define REG_PORT_PHY_CTRL		0x0100

#define PORT_PHY_RESET			BIT(15)
#define PORT_PHY_LOOPBACK		BIT(14)
#define PORT_SPEED_100MBIT		BIT(13)
#define PORT_AUTO_NEG_ENABLE		BIT(12)
#define PORT_POWER_DOWN			BIT(11)
#define PORT_ISOLATE			BIT(10)
#define PORT_AUTO_NEG_RESTART		BIT(9)
#define PORT_FULL_DUPLEX		BIT(8)
#define PORT_COLLISION_TEST		BIT(7)
#define PORT_SPEED_1000MBIT		BIT(6)

#define REG_PORT_PHY_STATUS		0x0102

#define PORT_100BT4_CAPABLE		BIT(15)
#define PORT_100BTX_FD_CAPABLE		BIT(14)
#define PORT_100BTX_CAPABLE		BIT(13)
#define PORT_10BT_FD_CAPABLE		BIT(12)
#define PORT_10BT_CAPABLE		BIT(11)
#define PORT_EXTENDED_STATUS		BIT(8)
#define PORT_MII_SUPPRESS_CAPABLE	BIT(6)
#define PORT_AUTO_NEG_ACKNOWLEDGE	BIT(5)
#define PORT_REMOTE_FAULT		BIT(4)
#define PORT_AUTO_NEG_CAPABLE		BIT(3)
#define PORT_LINK_STATUS		BIT(2)
#define PORT_JABBER_DETECT		BIT(1)
#define PORT_EXTENDED_CAPABILITY	BIT(0)

#define REG_PORT_PHY_ID_HI		0x0104
#define REG_PORT_PHY_ID_LO		0x0106

#define LAN937X_ID_HI			0x0007
#define LAN937X_ID_LO			0x1951

#define REG_PORT_PHY_1000_CTRL		0x0112
#define PORT_AUTO_NEG_MANUAL			BIT(12)
#define PORT_AUTO_NEG_M		BIT(11)
#define PORT_AUTO_NEG_M_PREFERRED	BIT(10)
#define PORT_AUTO_NEG_1000BT_FD		BIT(9)
#define PORT_AUTO_NEG_1000BT			BIT(8)

#define REG_PORT_PHY_1000_STATUS	0x0114

#define REG_PORT_PHY_RXER_COUNTER	0x012A
#define REG_PORT_PHY_INT_ENABLE		0x0136
#define REG_PORT_PHY_INT_STATUS		0x0137

/* Same as PORT_PHY_LOOPBACK */
#define PORT_PHY_PCS_LOOPBACK		BIT(0)

#define REG_PORT_PHY_DIGITAL_DEBUG_2	0x013A

#define REG_PORT_PHY_DIGITAL_DEBUG_3	0x013C
#define PORT_100BT_FIXED_LATENCY	BIT(15)

#define REG_PORT_PHY_PHY_CTRL		0x013E
#define PORT_INT_PIN_HIGH		BIT(14)
#define PORT_ENABLE_JABBER		BIT(9)
#define PORT_STAT_SPEED_1000MBIT	BIT(6)
#define PORT_STAT_SPEED_100MBIT		BIT(5)
#define PORT_STAT_SPEED_10MBIT		BIT(4)
#define PORT_STAT_FULL_DUPLEX		BIT(3)

/* Same as PORT_PHY_STAT_M */
#define PORT_STAT_M		BIT(2)
#define PORT_RESET			BIT(1)
#define PORT_LINK_STATUS_FAIL		BIT(0)

/* 3 - xMII */
#define REG_PORT_XMII_CTRL_0		0x0300
#define PORT_SGMII_SEL			BIT(7)
#define PORT_MII_FULL_DUPLEX		BIT(6)
#define PORT_MII_TX_FLOW_CTRL		BIT(5)
#define PORT_MII_100MBIT		BIT(4)
#define PORT_MII_RX_FLOW_CTRL		BIT(3)
#define PORT_GRXC_ENABLE		BIT(0)

#define REG_PORT_XMII_CTRL_1		0x0301
#define PORT_MII_NOT_1GBIT		BIT(6)
#define PORT_MII_SEL_EDGE		BIT(5)
#define PORT_RGMII_ID_IG_ENABLE		BIT(4)
#define PORT_RGMII_ID_EG_ENABLE		BIT(3)
#define PORT_MII_MAC_MODE		BIT(2)
#define PORT_MII_SEL_M			0x3
#define PORT_RGMII_SEL			0x0
#define PORT_RMII_SEL			0x1
#define PORT_MII_SEL			0x2

#define REG_PORT_XMII_CTRL_2		0x0302
#define PORT_RGMII_RX_STS_ENABLE	BIT(0)

#define REG_PORT_XMII_CTRL_4		0x0304
#define REG_PORT_XMII_CTRL_5		0x0305

/* 4 - MAC */
#define REG_PORT_MAC_CTRL_0		0x0400
#define PORT_CHECK_LENGTH		BIT(2)
#define PORT_BROADCAST_STORM		BIT(1)
#define PORT_JUMBO_PACKET		BIT(0)

#define REG_PORT_MAC_CTRL_1		0x0401
#define PORT_BACK_PRESSURE		BIT(3)
#define PORT_PASS_ALL			BIT(0)

#define REG_PORT_MAC_CTRL_2		0x0402
#define PORT_100BT_EEE_DISABLE		BIT(7)
#define PORT_1000BT_EEE_DISABLE		BIT(6)

#define REG_PORT_MAC_IN_RATE_LIMIT	0x0403

#define REG_PORT_MTU__2			0x0404
#define PORT_RATE_LIMIT_M		(BIT(7) - 1)

/* 5 - MIB Counters */
#define REG_PORT_MIB_CTRL_STAT__4	0x0500
#define MIB_COUNTER_OVERFLOW		BIT(31)
#define MIB_COUNTER_VALID		BIT(30)
#define MIB_COUNTER_READ		BIT(25)
#define MIB_COUNTER_FLUSH_FREEZE	BIT(24)
#define MIB_COUNTER_INDEX_M		(BIT(8) - 1)
#define MIB_COUNTER_INDEX_S		16
#define MIB_COUNTER_DATA_HI_M		0xF

#define REG_PORT_MIB_DATA		0x0504

/* 8 - Classification and Policing */
#define REG_PORT_MRI_MIRROR_CTRL	0x0800
#define PORT_MIRROR_RX			BIT(6)
#define PORT_MIRROR_TX			BIT(5)
#define PORT_MIRROR_SNIFFER		BIT(1)

#define REG_PORT_MRI_PRIO_CTRL		0x0801
#define PORT_HIGHEST_PRIO		BIT(7)
#define PORT_OR_PRIO			BIT(6)
#define PORT_MAC_PRIO_ENABLE		BIT(4)
#define PORT_VLAN_PRIO_ENABLE		BIT(3)
#define PORT_802_1P_PRIO_ENABLE		BIT(2)
#define PORT_DIFFSERV_PRIO_ENABLE	BIT(1)
#define PORT_ACL_PRIO_ENABLE		BIT(0)

#define REG_PORT_MRI_MAC_CTRL		0x0802
#define PORT_USER_PRIO_CEILING		BIT(7)
#define PORT_DROP_NON_VLAN		BIT(4)
#define PORT_DROP_TAG			BIT(3)
#define PORT_BASED_PRIO_M		KS_PRIO_M
#define PORT_BASED_PRIO_S		0

#define REG_PORT_MRI_TC_MAP__4		0x0808

/* 9 - Shaping */
#define REG_PORT_MTI_QUEUE_INDEX__4	0x0900

#define REG_PORT_MTI_QUEUE_CTRL_0__4	0x0904
#define MTI_PVID_REPLACE		BIT(0)

#define REG_PORT_MTI_QUEUE_CTRL_0	0x0914

/* A - QM */
#define REG_PORT_QM_CTRL__4		0x0A00
#define PORT_QM_DROP_PRIO_M		0x3

#define REG_PORT_VLAN_MEMBERSHIP__4	0x0A04

#define REG_PORT_QM_QUEUE_INDEX__4	0x0A08
#define PORT_QM_QUEUE_INDEX_S		24
#define PORT_QM_BURST_SIZE_S		16
#define PORT_QM_MIN_RESV_SPACE_M	(BIT(11) - 1)

#define REG_PORT_QM_WATER_MARK__4	0x0A0C
#define PORT_QM_HI_WATER_MARK_S		16
#define PORT_QM_LO_WATER_MARK_S		0
#define PORT_QM_WATER_MARK_M		(BIT(11) - 1)

#define REG_PORT_QM_TX_CNT_0__4		0x0A10
#define PORT_QM_TX_CNT_USED_S		0
#define PORT_QM_TX_CNT_M		(BIT(11) - 1)

#define REG_PORT_QM_TX_CNT_1__4		0x0A14
#define PORT_QM_TX_CNT_CALCULATED_S	16
#define PORT_QM_TX_CNT_AVAIL_S		0

/* B - LUE */
#define REG_PORT_LUE_CTRL		0x0B00

#define PORT_VLAN_LOOKUP_VID_0		BIT(7)
#define PORT_INGRESS_FILTER		BIT(6)
#define PORT_DISCARD_NON_VID		BIT(5)
#define PORT_MAC_BASED_802_1X		BIT(4)
#define PORT_SRC_ADDR_FILTER		BIT(3)

#define REG_PORT_LUE_MSTP_INDEX		0x0B01

#define REG_PORT_LUE_MSTP_STATE		0x0B04

#define PORT_TX_ENABLE			BIT(2)
#define PORT_RX_ENABLE			BIT(1)
#define PORT_LEARN_DISABLE		BIT(0)

#define REG_PORT_LUE_LEARN_CNT__2	0x0B08

#define REG_PORT_LUE_UNK_UCAST_CTRL__2	0x0B0E
#define REG_PORT_LUE_UNK_MCAST_CTRL__2	0x0B10
#define REG_PORT_LUE_UNK_VID_CTRL__2	0x0B12

#define PORT_UNK_UCAST_ENABLE		BIT(15)
#define PORT_UNK_MCAST_ENABLE		BIT(15)
#define PORT_UNK_VID_ENABLE		BIT(15)

#define PRIO_QUEUES			8
#define RX_PRIO_QUEUES			8
#define KS_PRIO_IN_REG			2
#define TOTAL_PORT_NUM			8

#define LAN937X_COUNTER_NUM		0x20
#define TOTAL_LAN937X_COUNTER_NUM	(LAN937X_COUNTER_NUM + 2 + 2)

#define SWITCH_COUNTER_NUM		LAN937X_COUNTER_NUM

#define P_BCAST_STORM_CTRL		REG_PORT_MAC_CTRL_0
#define P_PRIO_CTRL			REG_PORT_MRI_PRIO_CTRL
#define P_MIRROR_CTRL			REG_PORT_MRI_MIRROR_CTRL
#define P_STP_CTRL			REG_PORT_LUE_MSTP_STATE
#define P_PHY_CTRL			REG_PORT_PHY_CTRL
#define P_NEG_RESTART_CTRL		REG_PORT_PHY_CTRL
#define P_LINK_STATUS			REG_PORT_PHY_STATUS
#define P_SPEED_STATUS			REG_PORT_PHY_PHY_CTRL
#define P_RATE_LIMIT_CTRL		REG_PORT_MAC_IN_RATE_LIMIT

#define S_LINK_AGING_CTRL		REG_SW_LUE_CTRL_1
#define S_MIRROR_CTRL			REG_SW_MRI_CTRL_0
#define S_REPLACE_VID_CTRL		REG_SW_MAC_CTRL_2
#define S_802_1P_PRIO_CTRL		REG_SW_MAC_802_1P_MAP_0
#define S_TOS_PRIO_CTRL			REG_SW_MAC_TOS_PRIO_0
#define S_FLUSH_TABLE_CTRL		REG_SW_LUE_CTRL_1

#define REG_SWITCH_RESET		REG_RESET_CTRL

#define SW_FLUSH_DYN_MAC_TABLE		SW_FLUSH_MSTP_TABLE

#define MAX_TIMESTAMP_UNIT		2
#define MAX_TRIG_UNIT			3
#define MAX_TIMESTAMP_EVENT_UNIT	8
#define MAX_GPIO			2
#define MAX_CLOCK			2

#define PTP_TRIG_UNIT_M			(BIT(MAX_TRIG_UNIT) - 1)
#define PTP_TS_UNIT_M			(BIT(MAX_TIMESTAMP_UNIT) - 1)

#define TAIL_TAG_PTP			BIT(7)
#define TAIL_TAG_NEXT_CHIP		BIT(6)
#define TAIL_TAG_K2L			BIT(5)
#define TAIL_TAG_PTP_1_STEP		BIT(4)
#define TAIL_TAG_PTP_P2P		BIT(3)
#define TAIL_TAG_RX_PORTS_M		0x7

/* 148,800 frames * 67 ms / 100 */
#define BROADCAST_STORM_VALUE		9969

#define SW_CHECK_LENGTH			BIT(3)

#define FR_MIN_SIZE		1522
#define FR_MAX_SIZE		9000

#define PORT_JUMBO_EN			BIT(0)
#define PORT_FR_CHK_LENGTH		BIT(2)
#define PORT_MAX_FR_SIZE		0x404

#define FR_SIZE_CPU_PORT		1540

#define REG_PORT_CTRL_0				0x0020
#define PORT_MAC_LOOPBACK			BIT(7)
#define PORT_FORCE_TX_FLOW_CTRL		BIT(5)
#define PORT_FORCE_RX_FLOW_CTRL		BIT(3)

#define PORT_QUEUE_SPLIT_ENABLE		0x3

/* Get fid from vid, fid 0 is not used if vid is greater than 127 */
#define LAN937X_GET_FID(vid)	(((vid) % ALU_FID_SIZE) + 1)

/* Driver set switch broadcast storm protection at 10% rate. */
#define BROADCAST_STORM_PROT_RATE	10

#define MII_BMSR_100BASE_TX_FD		BIT(14)

#define PHY_LINK_UP					1
#define PHY_LINK_DOWN				0

/*The port number as per the datasheet*/
#define RGMII_2_PORT_NUM		5
#define RGMII_1_PORT_NUM		6
#define SGMII_PORT_NUM			4
#define TXPHY_PORT_NUM			4

#define GET_CHIP_ID_LSB(chip_id)	(((chip_id) >> 8) & 0xff)
#define LAN937X_RGMII_2_PORT		(RGMII_2_PORT_NUM - 1)
#define LAN937X_RGMII_1_PORT		(RGMII_1_PORT_NUM - 1)
#define LAN937X_SGMII_PORT			(SGMII_PORT_NUM - 1)
#define LAN937X_TXPHY_PORT			(TXPHY_PORT_NUM - 1)

#endif
