#!/bin/sh
#
# Configure the T1 Phy mode master/slave
#

configure_t1phymode() {
    if [ -e "/sys/class/net/lan1" ]; then
        ETHDEV=lan
        START=1
        p=2
        while [ -e "/sys/class/net/lan$p" ]; do
            let p=$p+1
        done
        PORTS=$p
    fi

    mode=$(cat /proc/cmdline | awk -F"phymode=" '{print $2}' | awk -F" " '{ print $1 }')
    if [ "$mode" = "master" ]; then
	    phymode="forced-master"
    else
	    phymode="forced-slave"
    fi

    p=$START
    while [ $p -lt $PORTS ]; do
	ethtool -s $ETHDEV$p master-slave $phymode
        let p=$p+1
    done

}

start() {
    configure_t1phymode
}

case "$1" in
    start)
        start
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
