meld drivers/net/dsa/microchip ../../lan_937x_linux_dsa/src/kernels/masternet-next/drivers/net/dsa/microchip/
meld drivers/net/phy/microchip_t1.c ../../lan_937x_linux_dsa/src/kernels/masternet-next/drivers/net/phy/microchip_t1.c 
meld net/dsa/tag_ksz.c ../../lan_937x_linux_dsa/src/kernels/masternet-next/net/dsa/tag_ksz.c
meld MAINTAINERS ../../lan_937x_linux_dsa/src/kernels/masternet-next/MAINTAINERS
meld include/net/dsa.h ../../lan_937x_linux_dsa/src/kernels/masternet-next/include/net/dsa.h
meld net/dsa/Kconfig ../../lan_937x_linux_dsa/src/kernels/masternet-next/net/dsa/Kconfig                             
meld net/dsa/tag_ksz.c ../../lan_937x_linux_dsa/src/kernels/masternet-next/net/dsa/tag_ksz.c
meld drivers/net/ethernet/cadence/macb_main.c ../../lan_937x_linux_dsa/src/kernels/masternet-next/drivers/net/ethernet/cadence/macb_main.c
meld drivers/base/regmap/regmap-debugfs.c ../../lan_937x_linux_dsa/src/kernels/masternet-next/drivers/base/regmap/regmap-debugfs.c