#ifndef __PM_DATA_OFFSETS_H__
#define __PM_DATA_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */

#define PM_DATA_PMC 0 /* offsetof(struct at91_pm_data, pmc) */
#define PM_DATA_RAMC0 4 /* offsetof(struct at91_pm_data, ramc[0]) */
#define PM_DATA_RAMC1 8 /* offsetof(struct at91_pm_data, ramc[1]) */
#define PM_DATA_MEMCTRL 16 /* offsetof(struct at91_pm_data, memctrl) */
#define PM_DATA_MODE 20 /* offsetof(struct at91_pm_data, mode) */
#define PM_DATA_SHDWC 24 /* offsetof(struct at91_pm_data, shdwc) */
#define PM_DATA_SFRBU 28 /* offsetof(struct at91_pm_data, sfrbu) */
#define PM_DATA_PMC_MCKR_OFFSET 40 /* offsetof(struct at91_pm_data, pmc_mckr_offset) */
#define PM_DATA_PMC_VERSION 44 /* offsetof(struct at91_pm_data, pmc_version) */

#endif
